Add playwright workflow (#334)
* Add playwright workflow

* Remove redundant steps

* Fix credentials

* Fix artefacts

* Fix order

* Remove defaults

* fix folder names

* Fix spaces

* Spacings

* Fix defaults

* Fix if

---------

Co-authored-by: Rsengo <rudentsov@mindbox.cloud>

diff --git a/.github/workflows/frontend_e2e.yml b/.github/workflows/frontend_e2e.yml
--- a/.github/workflows/frontend_e2e.yml
+++ b/.github/workflows/frontend_e2e.yml
@@ -28,6 +28,11 @@ on:
         default: "dev_new_frontend"
         required: false
         type: string
+      playwright_image_name:
+        description: "playwright e2e image name"
+        default: "dev_new_frontend"
+        required: false
+        type: string
       core_project:
         description: "True if project is frontend_core_v2"
         default: false
@@ -43,6 +48,11 @@ on:
         default: false
         required: false
         type: boolean
+      e2e_runner:
+        description: "E2E runner"
+        default: "cypress"
+        required: false
+        type: string
     secrets:
       npm_token:
         description: "A GH_NPM_REGISTRY token passed from the caller workflow"
@@ -65,6 +75,12 @@ on:
       kube_dev_config_k8:
         description: "A SA_TOKEN_DTLN_KUBE_CDP_STAGING_MICROFRONTENDS token passed from the caller workflow for new deploy"
         required: false
+      e2e_adminsite_username:
+        description: "Username for admin site e2e test user"
+        required: false
+      e2e_adminsite_password:
+        description: "Password for admin site e2e test user"
+        required: false
       kube_token:
         description: "A SA_TOKEN_RU_STAGING_YC_KUBE_CDP_MIXED1_MICROFRONTENDS token passed from the caller workflow for deploy"
         required: true
@@ -77,9 +93,6 @@ jobs:
     timeout-minutes: 20
     runs-on: ubuntu-latest
     env:
-      retries: ${{ inputs.retries }}
-      CYPRESS_username: "${{ secrets.cypress_login }}"
-      CYPRESS_password: "${{ secrets.cypress_pass }}"
       registry: cr.yandex/${{ inputs.registry_id }}
       image: ${{ inputs.image_name }}
 
@@ -183,7 +196,7 @@ jobs:
           echo "The DNS CNAME record for 'e2e-testing-${{ env.hash_payload }}-staging.mindbox.ru' was not created as expected."
           exit 1
 
-  e2e-tests:
+  e2e-tests-cypress:
     runs-on: [self-hosted, frontend]
     container:
       image: cr.yandex/crpo9tj76o3c7pi8i72n/cached/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
@@ -284,6 +297,60 @@ jobs:
           path: e2e/cypress
           retention-days: 1
 
+  e2e-tests-playwright:
+    runs-on: [self-hosted, frontend]
+    needs: prepare-site
+    timeout-minutes: ${{ inputs.e2e-timeout }}
+    if: ${{ always() && !cancelled() && !inputs.core_project && inputs.e2e_runner == 'playwright' }}
+    env:
+      image: frontend-e2e-pr
+
+    steps:
+      - uses: technote-space/workflow-conclusion-action@v3
+      - name: check fail
+        if: env.WORKFLOW_CONCLUSION == 'failure'
+        run: echo "previous steps are failed" && exit 1
+
+      - name: Checkout the repository
+        uses: actions/checkout@v4
+
+      - name: Set variables
+        run: |
+          echo "ref_name=$(echo $GITHUB_HEAD_REF | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
+          echo "repository_name=$(cat $GITHUB_EVENT_PATH | jq '.repository.name' | sed 's/\"//g')" >> $GITHUB_ENV
+        id: set_variables
+
+      - name: Get branch and repo names hash
+        run: echo "hash_payload=$(echo $BRANCH_AND_REPO | md5sum | sed 's/  -//g')"  >> $GITHUB_ENV
+        id: branch_and_repo_hash
+        env:
+          BRANCH_AND_REPO: "${{ env.repository_name }} ${{ env.ref_name }}"
+
+      - name: Build docker image
+        run: docker build . -t ${{ env.image }}:${{ env.hash_payload }}
+        working-directory: ./playwright
+
+      - name: Run E2E tests on not core project.
+        run: |
+          [ -d ./playwright-results ] && mkdir -p ./playwright-results
+          mkdir -p ./playwright-results/test-results && mkdir -p ./playwright-results/report
+          docker run -i \
+            -e BASE_URL="https://e2e-testing-${{ env.hash_payload }}-staging.mindbox.ru" \
+            -e RETRIES="${{ env.retries }}" \
+            -e ADMINSITE_USERNAME=${{ secrets.e2e_adminsite_username }} \
+            -e ADMINSITE_PASSWORD=${{ secrets.e2e_adminsite_password }} \
+            -v $(pwd)/playwright-results/report:/e2e/playwright-report \
+            -v $(pwd)/playwright-results/test-results:/e2e/test-results \
+            ${{ env.image }}:${{ env.hash_payload }} 2>&1
+
+      - name: Upload test results artifacts
+        uses: actions/upload-artifact@v4
+        if: ${{ failure() }}
+        with:
+          name: playwright-${{ env.project_name }}
+          path: playwright-report
+          retention-days: 1
+
   core-e2e-tests-matrix:
     runs-on: ubuntu-latest
     needs: prepare-site
@@ -350,6 +417,7 @@ jobs:
           - campaigns
           - retail
           - auth-page
+          - email-editor-playwright
       max-parallel: 4
     timeout-minutes: ${{ inputs.e2e-timeout }}
     if: ${{ always() && !cancelled() && inputs.core_project }}
@@ -423,6 +491,9 @@ jobs:
             -e CYPRESS_password=${{ secrets.cypress_pass }} \
             -e CYPRESS_grepTags="@smoke" \
             -e CYPRESS_grepOmitFiltered=true \
+            -e ADMINSITE_USERNAME=${{ secrets.e2e_adminsite_username }} \
+            -e ADMINSITE_PASSWORD=${{ secrets.e2e_adminsite_password }} \
+            -e GREP_TAGS="@smoke" \
             -v $(pwd)/cypress/${{ matrix.project }}/videos:/e2e/cypress/videos \
             -v $(pwd)/cypress/${{ matrix.project }}/screenshots:/e2e/cypress/screenshots \
             cr.yandex/${{ inputs.registry_id }}/frontend-e2e:${{ matrix.project }}-latest 2>&1
@@ -439,7 +510,7 @@ jobs:
 
   post-e2e-tests:
     runs-on: ubuntu-latest
-    needs: [e2e-tests, core-e2e-tests-runner]
+    needs: [e2e-tests-cypress, e2e-tests-playwright, core-e2e-tests-runner]
     if: ${{ failure() }}
     steps:
       - name: Add comment to commit if the job has failed
@@ -450,8 +521,8 @@ jobs:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
 
   clean-up-e2e-tests:
-    needs: [e2e-tests, core-e2e-tests-runner]
-    if: ${{ always() && ( needs.e2e-tests.result == 'success' || needs.core-e2e-tests-runner.result == 'success' ) }}
+    needs: [e2e-tests-cypress, e2e-tests-playwright, core-e2e-tests-runner]
+    if: ${{ always() && (needs.e2e-tests-cypress.result == 'success' && (inputs.e2e_runner != 'playwright' || needs.e2e-tests-playwright.result == 'success') || needs.core-e2e-tests-runner.result == 'success') }}
     uses: mindbox-cloud/github-actions/.github/workflows/frontend_cleanup_testing.yml@master
     with:
       hot_testing: false
